### ISSUE TITLE
Release Thread 2

### ISSUE THREAD

**Issue by Mayegelt** [BSData/horus-heresy#2050]
Data Developers - Please use this issue to push new releases if doing so via comment.

Explainer
Create an issue comment that starts with /release on the first line.
Second (non-empty) line will be used as a release title/name.
All following lines will be interpreted as a release description/body.
Description (even if empty) will always be appended with a comparison link to the previous release, unless there is no previous release.
How to
Add a comment with one of the following to push a release:

For a standard release:
given latest release v1.0,0 will create a release v1.0.1 (increases patch)

/release
PUT THE TITLE HERE (This is title of v1.0.1)

For a New Book / Big FAQ initial releases (game-wide updates):
given latest release v1.0,0 will create a release v1.1.0 (increases minor, resets patch)

/release bump=minor
PUT THE TITLE HERE (This is title of v1.1.0)

For a new game edition:
given latest release v1.0,0 will create a release v2.0.0 (increases major, resets minor and patch)

/release bump=major
PUT THE TITLE HERE (This is title of v2.0.0)

**Comment by Mayegelt** [comment]
/release
Maybe the last one for HH 1.0

**Comment by Technoblazed** [comment]
/release
Test

**Comment by Mayegelt** [comment]
/release
New EC, New WS maybe no more updates till 2.0

**Comment by Mayegelt** [comment]
/release
Various fixes, not much more till retirement.
Some LoW choices fixed for Knights in armies.
Mournival fix for vet recon squads,
Gal Vorbak weapon options fix
Sun Killers special rule fixed (due to rewording after initial release)
3rd Company Elite fix for Compulsory units.

**Comment by Mayegelt** [comment]
/release
Ravenguard get some love!
Added new RG unit.

**Comment by Mayegelt** [comment]
/release
Ravenguard new unit Melta cost fix
Ravenguard new unit Melta cost fix

**Comment by Mayegelt** [comment]
/release
Contekar, Knight Crusader and Narik Dreygur
Fixes for Contekar dedicated Transports
Knight Crusader weapon options
Narik Dreygur selection, robots and vets options.

**Comment by Mayegelt** [comment]
/release
Wednesday Update, a few more units, still ages to go.

**Comment by Mayegelt** [comment]
/release
Hay look. More stuff done. Probably even more tomorrow!

**Comment by Mayegelt** [comment]
/release
Placeholder PTS
Added some placeholder pts for various universal units.
Later I'll add ones for LoW and the Exemplary Battles and Legends stuff.
All these things will help people build lists while we take time getting all the rules and profiles in.

**Comment by Mayegelt** [comment]
/release
Placeholder PTS (Please delete existing data when refreshing)
Added some placeholder pts for various universal units.
Later I'll add ones for LoW and the Exemplary Battles and Legends stuff.
All these things will help people build lists while we take time getting all the rules and profiles in.

**Comment by Mayegelt** [comment]
/release
Quick fix for Breacher and Recon as well as pts for Placeholders

**Comment by Mayegelt** [comment]
/release
More Placeholders and Universal Troops and Fast Attack should be fully working

**Comment by Mayegelt** [comment]
/release
Lots of little fixes from feedback.

**Comment by Mayegelt** [comment]
/release
More units and options. Its slowly coming together.

**Comment by nstephenh** [comment]
/release 
More units that hopefully doesn't break anything

**Comment by Mayegelt** [comment]
/release
Mini patch to fix a couple of issues

**Comment by Mayegelt** [comment]
/release bump=minor
Iron Warriors got there own cat! Also unit fixes and additions

**Comment by Mayegelt** [comment]
/release
More small fixes on yesterdays stuff.

**Comment by UrsinePatriarch** [comment]
/release
More catz than an octogenarian widow; all Legions now have a separate catalog!

**Comment by UrsinePatriarch** [comment]
/release
Blessed is he who guides this blessed machine; here's the start of our Knight/Titan lists! AdMech to follow ~

**Comment by UrsinePatriarch** [comment]
/release
The Machine God endows thee with life; AdMech updates, Knights-Errant, WLTs, & more LsoW!

**Comment by UrsinePatriarch** [comment]
/release
The Greater Splittening! All Legions now have their own root entries, so we _shouldn't_ see any more repeating entries. Oh yeah, and AdMech is mostly done, definitely not a huge deal or anything.

**Comment by alphalas** [comment]
/release
2 releases in 12 hours! 
Fixes overzealous constraints forcing some primarchs and characters, and headhunters costs.

**Comment by UrsinePatriarch** [comment]
/release
3 releases in as many days! What is this world coming to? (More bugfixes before the weekly release).

**Comment by UrsinePatriarch** [comment]
/release
The start of something great; RoW basic implementation! Expect full rollout sometime soon ~

**Comment by UrsinePatriarch** [comment]
/release
Much ado about... a whole lot, actually! Lots of Reformats and fixes across the board.

**Comment by UrsinePatriarch** [comment]
/release
Bugfixes as we work on Rites of War; nothing else to report.

**Comment by Mayegelt** [comment]
/release
It's been 3 long weeks, but we are still working v2
Had an issue of a couple of things missing, this fixes it.

**Comment by Mayegelt** [comment]
/release bump=minor
All Universal RoW now fully operational. Legion Specific ones are WS and a couple of DA.

**Comment by Mayegelt** [comment]
/release
All Universal RoW now fully operational. Only legion ones are WS and a couple of DA. v2
Fixed a bunch of compulsory troop options, a couple of consuls, nullificators, a couple of BA equipment costs.

**Comment by Mayegelt** [comment]
/release bump=minor
All RoW done apart from Alpha Legion. SA, SoS, Assassin done. Custodes placeholders.

**Comment by Mayegelt** [comment]
/release
Fixes for v16.4.0

**Comment by Mayegelt** [comment]
/release bump=minor
What's that? All RoW done including AL!

**Comment by Mayegelt** [comment]
/release
Custodes should be complete... I think only Allies and ZM to go.

**Comment by Mayegelt** [comment]
/release bump=minor
Zone Mortalis is here!

**Comment by Mad-Spy** [comment]
/release bump=minor
Zone Mortalis is here!

**Comment by Mayegelt** [comment]
/release
Fixes for various bits and more ZM bits

**Comment by Mayegelt** [comment]
/release bump=minor
PANIC/REJOICE DAEMONS HAVE INVADED/ARRIVED!

**Comment by Mayegelt** [comment]
/release
REJOICE/PANIC DAEMONS HAVE ARRIVED/INVADED! (Legions get Daemons)

**Comment by Mayegelt** [comment]
/release
Little fixes for mainly DA and EC

**Comment by Mayegelt** [comment]
/release
Fixes for Whirlwinds, DG Levi, Templar Melta Bombs

**Comment by Mayegelt** [comment]
/release
A few more minor fixes for pts and selections

**Comment by Mayegelt** [comment]
/release
Minor fixes. Hopefully Imperial Militia next.

**Comment by Mayegelt** [comment]
/release
More minor fixes. Hopefully Imperial Militia soon. Sorry for the delay

**Comment by Mayegelt** [comment]
/release bump=minor
Whole lot of fixes, and Militia

Militia probably needs some reworking for ease of use, but the core should all be there and working now.

**Comment by Mayegelt** [comment]
/release bump=minor
The Siege is upon us!
Inductii now added along with all other SoC content.  #2847 
Additionally a whole bunch of fixes #2843 #2846 #2852 #2853 #2854 #2855 #2859 #2860 #2861 #2862

**Comment by Mayegelt** [comment]
/release
No bug reports in a week... are we done?

**Comment by Mayegelt** [comment]
/release
So we weren't done
Fixes for #2867 #2868 #2869 #2870 #2872

**Comment by Mayegelt** [comment]
/release
Probably no more fixes for a month!
Fixes for #2873 #2874 #2875 #2877

**Comment by The4D6** [comment]
/release
Couple fo quick fixes to missing profiles and unit types
Fixes for #2881 #2880

**Comment by Mayegelt** [comment]
/release
Couple of quick fixes to missing profiles and unit types
Fixes for #2881 #2880

**Comment by nstephenh** [comment]
/release bump=major
Remove Heresy 1.0 (you may need to clean up the existing files yourself).
Heresy 1.0 can now be accessed here: https://github.com/BSData/horus-heresy-1e or through gallery and appspot (if appspot works).
Also includes fixes for:
Secutors
Vulkan
Excindo battle automata
Red Hand Destroyer Ravager
#2884 ZM Elite Restriction
#2885 DA Excindo
#2886 Independant Char on Special Chars affecting wargear options on retinues.
#2887 Master of Signal
#2888 Pursuer Cadre beasts
#2897 Command Squad and Lightning Claws on bikes
#2899 AL and Deathshroud
#2900 Carsoran Power Tabar rule
#2901 Reaver aggressors special weapons
#2902 IF Castellon and Armistos Heavy Subtype.
#2904 Tsolmon Khan and knight centura
#2907 Suzerians profiles
Fix for WS files as duplicate ID was found in catalogue links Fix for Militia as issue of link was missing.

**Comment by Mayegelt** [comment]
/release
Minor fixes, mainly PTS and choices

**Comment by nstephenh** [comment]
/release minor
Added Corrupted Engines. Cyburtheurgies may need to be reselected.

**Comment by Mayegelt** [comment]
/release bump=minor
Fixes. Maybe next update will be Fulgrim Ascended

**Comment by Mayegelt** [comment]
/release bump=minor
Exemplary Traitor Knights

**Comment by Mayegelt** [comment]
/release
Fixes for PTS for Dark Blessings

**Comment by Mayegelt** [comment]
/release
More fixes for dark blessing, and Castellan HSS

**Comment by Mayegelt** [comment]
/release
Narik Dreygur is a Praevian

**Comment by Mayegelt** [comment]
/release bump=minor
LoW have moved, Daemons are upon us! (but not the links for Esoterist, Lorgar or Erebus yet)

**Comment by Mayegelt** [comment]
/release
LoW moved last release & Daemons are still upon us, but are now more numerous!

**Comment by Mayegelt** [comment]
/release
Many little fixes before the next book release.

**Comment by Mayegelt** [comment]
/release bump=minor
The Children of the Emperor are now more Heretical

**Comment by Mayegelt** [comment]
/release
Just a few fixes and making it easier to be heretical

**Comment by The4D6** [comment]
/release
Fixed the following things:
- Ruinstorm Daemon Brutes can no longer select more Infernal Armaments then there are brutes in a unit
- Ruinstorm Daemons can now select a psychic discipline with the Aetheric Conduit upgrade
- Phoenix Terminators are now correctly Bulky (2)
- Phoenix Terminators now have the correct rules if you select Legiones Hereticus
- Secutarii peltasts now have the Kyropatris Field Generator
- Day of Sorrows no longer gives units Fearless by mistake
- Militia Cargo-8s now have the correct cost for Armoured Containers, and you can select the number of additional pintle-mounted heavy stubbers correctly
- Sons of Horus can now select Carsoran power weapons on Assault, Despoiler, and Assault Destroyer squads

**Comment by The4D6** [comment]
/release

17.4.4 Release: New Militia Provenances

### 6 Issues Fixed
- Ruinstorm Daemons now correctly apply Hammer of Wrath when you select Infernal Tempest
- Militia Lieutenants no longer get BS5 under Legacy of the Great Crusade
- Militia Force Commanders now get Initiative 5 under Legacy of the Great Crusade
- Iron Warriors Dominators are no longer hidden due to other detachments having "Exemplary Units On" selected
- Fixed an erroneous issue with the White Scars praevian and movement values
- A selection of corrected typos

### 1 Feature Added
- Militia now have the ability to choose their new Provenances from the latest Exemplary Battles

Branch will be merged on 04/12/23

**Comment by The4D6** [comment]
/release

v18.0.1 - Only Rules and Horses

- Fixed an issue where the rules references for a number of things had disappeared due to a publication getting a new ID by mistake
- Fixed the Militia Cavalry unit having the wrong movement and missing some special rules

**Comment by The4D6** [comment]
/release

v18.0.2 - Hotfix #1

- Fixed Militia Cavalry sergeant having wrong movement also

**Comment by The4D6** [comment]
/release bump=minor

v18.1.0 - Futureproofing and Technical Gubbins

Features/improvements in this release:
- #3029 Some vehicles in the militia list have been properly linked to their original catalogue versions so changes will carry across properly

Issues fixed in this release:
- Various typos
- Legion Tarantula sentry gun points corrected
- Armoured Spearhead rite of war text has been updated tot he FAQ'd version
- #3048 Removed teleport strike from Indomitus Terminators
- #3049 Speakers of the Dead can now swap their MC poewr maul for a frost weapon correctly
- #3050 Sicaran accelerator autocannon now as the correct version of rending displayed
- #3051 Fixed missing praetorian breacher profile
- #3052 Nomus Rhy'Tan can now choose a retinue like any other Salamander's Master of the Legion
- #3055 Death Guard non-terminator centurions and praetors can now properly select alchem pistols

**Comment by The4D6** [comment]
/release

v18.1.1 - The Gang Fixes Some Bugs

Issues fixed in this release:
- #3058 Ruinstorm Daemons can now select Cults Abominatio, Davinite Lodge Priests,and Expeditionary Navigators (as they are technically available to all traitor forces)
- #3060 Deathstorm Drop Pods now get a weapon allocated to them by default, and cannot select more than one weapon
- #3063 Militia Gorgon mortars are now swapped with "Two pairs of" sponsons rather than "2x"
- #3065 Kakophoni sergeants can now properly select Phoenix Rapiers/Spears

Issues we are aware of and working on:
- #3064 Red Hand Destroyers 1-in-5 selections have a funny issue where if you change the selection of one of them, it changes them all

**Comment by nstephenh** [comment]
/release bump=minor

v18.3.0 - Minor fixes and militia allies cleanup

Larger changes:

- #3119  Children of the Maraviglia and Liberation force previously had two implementations and would have a validation error. They should now properly count militia units. This also removes the unnecessary checkbox from each of them.
- #3125 Armoured support tercio was incorrectly set up to have 1 unit of 3 instead of 3 units of 1. Now that this is fixed, the UI is consistent between all 3 options in NR.
- #3104 and #3117 removed rules that were dropped between legacy document revisions. 

Defaulting edge cases (mostly affects NR)
- #3121
- #3110


Typos and missing weapon profiles:

- #3116 
- #3122 
- #3108 
- #3118 
- #3106 
- #3115 
- #3096
- #3111

**Comment by nstephenh** [comment]
/release 
Hotfix solar auxilia for battlescribe, seems like links without IDs were breaking it.
As an apology have a Heavy Sentinel!

**Comment by nstephenh** [comment]
/release 
Fix knight dark blessings

**Comment by nstephenh** [comment]
/release bump=minor
Some small fixes, make centurion a model.

- Pintle-mounted -> Pintle Mounted
- Boltspitter incorrectly had blind linked.
- #3146 
- #3148 
- #3145 
- #3149
- #3153

**Comment by nstephenh** [comment]
/release
Optae and Lifewards 
These didn't make it in because we accidentally didn't merge lifewards and forgot to merge them. Additionally, there was an issue with a min/max set on solar auxilia tactical command, veletaris tercio, infantry tercio, and artillery tercio that caused 1 of each to default into lists. This has been fixed, though the max 3 condition for veletaris tercio has not been re-added.

**Comment by nstephenh** [comment]
/release
Max 3 Veletaris per Tercio fix

**Comment by The4D6** [comment]
/release
Added rules for Hibou Khan

**Comment by nstephenh** [comment]
/release 
Lots of little fixes

Fix Horus Aximand and 17 extra Optae appearing in Alpha Legion
Jarls and TS Psychic powers should now be properly available.
Fix Valdor
Fix Points on Rapier Carriers
Fix In disgrace all are equal
Fix Kharybdis assault claw hidden in Covenant of Fire

**Comment by The4D6** [comment]
/release
Bug Fixes and New Units

- Added overseer
- Optae can now be taken as a compulsory HQ choice
- Fixed quad launcher shell pricing
- Fixed penal cohort weapon selection issue
- Fixed iron pattern cohort cortex controller issues
- Fixed selection issues with WE Berserker option on centurions

**Comment by The4D6** [comment]
/release
Sanguiniary Guard!

- Added new Sanguiniary Guard exemplary battles unit

**Comment by nstephenh** [comment]
/release
 Shadrak Meduson and Banners for sanguinary guard and company command squads.
Also prevented sanguinary from showing up in alpha legion, and typo fixes.

**Comment by nstephenh** [comment]
/release 
Points for sanguinary guard banner

**Comment by Mayegelt** [comment]
/release
Whole load of fixes for lots of minor things.

https://github.com/BSData/horus-heresy/issues/3097
https://github.com/BSData/horus-heresy/issues/3301 
https://github.com/BSData/horus-heresy/issues/3112
https://github.com/BSData/horus-heresy/issues/3123 
https://github.com/BSData/horus-heresy/issues/3128 
https://github.com/BSData/horus-heresy/issues/3139
https://github.com/BSData/horus-heresy/issues/3162
https://github.com/BSData/horus-heresy/issues/3165
https://github.com/BSData/horus-heresy/issues/3177
https://github.com/BSData/horus-heresy/issues/3186
https://github.com/BSData/horus-heresy/issues/3261
https://github.com/BSData/horus-heresy/issues/3271

https://github.com/BSData/horus-heresy/issues/3279
https://github.com/BSData/horus-heresy/issues/3283

https://github.com/BSData/horus-heresy/issues/3284
https://github.com/BSData/horus-heresy/issues/3287
https://github.com/BSData/horus-heresy/issues/3289
https://github.com/BSData/horus-heresy/issues/3291
https://github.com/BSData/horus-heresy/issues/3292
https://github.com/BSData/horus-heresy/issues/3293
https://github.com/BSData/horus-heresy/issues/3295
https://github.com/BSData/horus-heresy/issues/3296
https://github.com/BSData/horus-heresy/issues/3297
https://github.com/BSData/horus-heresy/issues/3298
https://github.com/BSData/horus-heresy/issues/3299
https://github.com/BSData/horus-heresy/issues/3300
https://github.com/BSData/horus-heresy/issues/3301
https://github.com/BSData/horus-heresy/issues/3304

**Comment by The4D6** [comment]
/release

Selection of minor fixes:
#3312 
#3311 
#3309 
#3306 
#3305 
#3256 
#3253

**Comment by The4D6** [comment]
/release

Fixed:
- Tybalt Marr's weapon missing a name
- Hetaeron missing a bunch of rules
- Some weirdness around Aetheric dominion selections
- Mechanicum throwing errors around Lord of War detachments
- Sanctifiers missing weapon selections
- EC inductii can now be selected by  detachment using Legiones Hereticus

**Comment by Mayegelt** [comment]
/release bump=minor
Mars Attacks!

New stuff
- Martian Civil War book content added (warlord traits, techno-arcana, cyberthergy, Daemon engines...)
- Legiones Legacy v1.3 changes for Cassian Dracos, Xiaphas Jurr & Narik Dreygur
Fixes
- Legiones Auxilia for EC wasn't working for allied detachments
- Despoiler squads were showing as support squads on BS incorrectly
- Inductii were still not accessible for EC Hereticus
- Questoris Knights Compulsory Troops in 1 unique situation fix
- Master of Automata typo fix

**Comment by Mayegelt** [comment]
/release bump=minor
Shattered Legions and other stuff

New Stuff
- Shattered Legions
- Head of the Gorgon + Machinator Array
- Javs and Speeders Dragon Breath Flamers
- Sisters of Silence Combi Weapons

Fixes
- Levy squad leaders miscount
- Legions Auxilia for Legions Hereticus not allowed
- pride is our armour for ZM
- Scion of Retlaxi typo
- Iron Hands Grav Pistol fix, shouldn't have been allowed on centurion/praetors on bikes
- Iron Warriors: Veteran Squad Bolter/Shrapnel
- Kaedes Nex allowed in Blackshields

**Comment by Mayegelt** [comment]
/release
2 quick fixes

Fixes
Overseer in Blackshields
Gorgon Termy Armour fix

**Comment by Mayegelt** [comment]
/release
6 quick bug fixes (We didn't know they were issues as no one told us).

Fixes
Solar Aux Penal Colony issue
Alpharius retinues.
Justarian in RoT Weapons fix
Pathfinder Centurion Save
Kheron Ophion Warlord Trait
Drop Pod Assault RoW Mhara Gals, Incaendius and Osirons

**Comment by Mayegelt** [comment]
/release
Another batch of fixes.
Psyk-out Grenades fix
Sevetars warlord trait beta fix
void shield generator Typo
Kaedes Nex hidden bug
Company Command Squad Lightning Claw fix.

**Comment by Mayegelt** [comment]
/release
2 more fixes
Salamander Mantle & NL Terror Assault fixes

**Comment by Mayegelt** [comment]
/release
Company Command and a few other fixes

- Fix for Arlatax weapons
- Fix for Abaddon banestrike combi bolter
- Fix for Castellan which shouldn't have been allowed in Blackshields.
- Fix for Company Command Squad limitations.
- Fix for default weapon on Varagyr

**Comment by Mayegelt** [comment]
/release
Company Command Squad refix

The Augury Scanner, Nuncio and Banners ended up falling off accidently in the rework.

**Comment by The4D6** [comment]
/release bump=minor
Fixed a plethora of issues
- Legion Command Squad Standard Bearer could sometimes select the Weapons of Desperation options only available to Blackshields
- Garro's Edge of Truth rule was still saying he got Reach (1) when he has siince been given duellist's edge (1)
- Line command sections in a Penal cohort no longer have weapons claiming to be hidden when they obviously aren't
- The Mhara Ghal dreadnought no loner has the Blind special rule mysteriously appear on its profile
- Shattered Legions detachments should now be able to select a Rite of War
- Questoris Knights Styrix and Magaera now have ion shields on their profiles
- Blackshields players in ZM no longer get errors for not selecting HQ units when running In Disgrace Are Equal
- Some Space Wolves units were missing their Legiones Astartes rule; this has now been remedied
- You are now able to take that treacherous dog Horus Aximand as a compulsory HQ without getting errors
- Farith Redloss's warlord trait now reflects that he is indeed a Dreadwing unit and not a Deathwing unit

**Comment by The4D6** [comment]
/release bump=minor

Fixes Galore!
- Procurators now have to pay for their tainted weapons
- You now have to pay for the Procurant before you make him a Procurator
- Zardu Layak now actually has two blade slaves rather than one blade slave called "Two blade slaves", so they can take upgrades individually
- Procurators can now take transports
- Adherents and Sanctifiers can now purchase Fear (1) via The Awakening Fire
- 3rd legion Inductii who use Legiones Hereticus can now select charnabal weapons like their not-necessarily-loyalist-but-less-corrupted Legiones Astartes brethren
- Blood slaughterers taken via a Traitor Praevian's Legiones Cybernetica are now correctly labelled as fast attack choices
- Caestus Assault Rams can no loner select an infinite number of magna-melta cannons
- Allied detachments of Questori Shouseholds no longer need to take a compulsory HQ choice
- Blackshields in Zone Mortalis running the oath Pride is Our Armour now have the correct number of available Elites slots

**Comment by The4D6** [comment]
/release bump=minor
Fixed a bunch of stuff:
@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/8c1e0e96a89978f36f0afcda26e9afab2475a5b3) https://github.com/BSData/horus-heresy/issues/3527[: Command cadres can now take shotguns](https://github.com/BSData/horus-heresy/pull/3530/commits/8c1e0e96a89978f36f0afcda26e9afab2475a5b3)
[8c1e0e9](https://github.com/BSData/horus-heresy/pull/3530/commits/8c1e0e96a89978f36f0afcda26e9afab2475a5b3)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/3ee2cd4a283c2db2884708802e8fd31fca615476) https://github.com/BSData/horus-heresy/issues/3521[: Added 1-per-force to assassins](https://github.com/BSData/horus-heresy/pull/3530/commits/3ee2cd4a283c2db2884708802e8fd31fca615476)
[3ee2cd4](https://github.com/BSData/horus-heresy/pull/3530/commits/3ee2cd4a283c2db2884708802e8fd31fca615476)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/ba8068965f6e9cefe14a77738c431f03f62207cc) https://github.com/BSData/horus-heresy/issues/3519[: Plasma repeaters are now twin-linked not two handed](https://github.com/BSData/horus-heresy/pull/3530/commits/ba8068965f6e9cefe14a77738c431f03f62207cc)
[ba80689](https://github.com/BSData/horus-heresy/pull/3530/commits/ba8068965f6e9cefe14a77738c431f03f62207cc)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/a71dca30c8bcbd359002bf913eea04b405115ea3) https://github.com/BSData/horus-heresy/issues/3516[: Increased ZM troops allocation from 5 to 6](https://github.com/BSData/horus-heresy/pull/3530/commits/a71dca30c8bcbd359002bf913eea04b405115ea3)
[a71dca3](https://github.com/BSData/horus-heresy/pull/3530/commits/a71dca30c8bcbd359002bf913eea04b405115ea3)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/6ab999e69972252c41d30927dd0c1f28d47913cb) https://github.com/BSData/horus-heresy/issues/3515[: Brought Dreygur's attacks down to 3](https://github.com/BSData/horus-heresy/pull/3530/commits/6ab999e69972252c41d30927dd0c1f28d47913cb)
[6ab999e](https://github.com/BSData/horus-heresy/pull/3530/commits/6ab999e69972252c41d30927dd0c1f28d47913cb)

@The4D6
[Potentially](https://github.com/BSData/horus-heresy/pull/3530/commits/4809c8e985d83b0696acfd20e7a28b0573a3e8b7) [fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/4809c8e985d83b0696acfd20e7a28b0573a3e8b7) https://github.com/BSData/horus-heresy/issues/3514[: Qin Xa's command squad defaulting to chainfists](https://github.com/BSData/horus-heresy/pull/3530/commits/4809c8e985d83b0696acfd20e7a28b0573a3e8b7)
[4809c8e](https://github.com/BSData/horus-heresy/pull/3530/commits/4809c8e985d83b0696acfd20e7a28b0573a3e8b7)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/6c1710967454af595f08011544e370a8e18cbb14) https://github.com/BSData/horus-heresy/issues/3510[: Double dynat](https://github.com/BSData/horus-heresy/pull/3530/commits/6c1710967454af595f08011544e370a8e18cbb14)
[6c17109](https://github.com/BSData/horus-heresy/pull/3530/commits/6c1710967454af595f08011544e370a8e18cbb14)

@The4D6
[fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/660a33f6a0a192a22cffd697a2ca2a0fe7283e2c) https://github.com/BSData/horus-heresy/issues/3509[: Frenzon is no longer a responsible substance that can be…](https://github.com/BSData/horus-heresy/pull/3530/commits/660a33f6a0a192a22cffd697a2ca2a0fe7283e2c) 
[660a33f](https://github.com/BSData/horus-heresy/pull/3530/commits/660a33f6a0a192a22cffd697a2ca2a0fe7283e2c)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/46247c54869f226890f5f8e60f10d663a4ae08a6) https://github.com/BSData/horus-heresy/issues/3507[: Validation on SoH characters](https://github.com/BSData/horus-heresy/pull/3530/commits/46247c54869f226890f5f8e60f10d663a4ae08a6)
[46247c5](https://github.com/BSData/horus-heresy/pull/3530/commits/46247c54869f226890f5f8e60f10d663a4ae08a6)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/5cd9273795fdaa0fec629b3ce4c3534cf9821cea) https://github.com/BSData/horus-heresy/issues/3506[: Added aether fire blaster to ammitara](https://github.com/BSData/horus-heresy/pull/3530/commits/5cd9273795fdaa0fec629b3ce4c3534cf9821cea)
[5cd9273](https://github.com/BSData/horus-heresy/pull/3530/commits/5cd9273795fdaa0fec629b3ce4c3534cf9821cea)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/b18221ec36fa2d85863eb2db47553c299da00711) https://github.com/BSData/horus-heresy/issues/3493[: Removed Polux's warlord trait from Garius](https://github.com/BSData/horus-heresy/pull/3530/commits/b18221ec36fa2d85863eb2db47553c299da00711)
[b18221e](https://github.com/BSData/horus-heresy/pull/3530/commits/b18221ec36fa2d85863eb2db47553c299da00711)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/3ae8fdc91732faf7c48971e2db3fb79d2cf28d64) https://github.com/BSData/horus-heresy/issues/3487[: Removed comp troops from crimson paladins in day of sorrows](https://github.com/BSData/horus-heresy/pull/3530/commits/3ae8fdc91732faf7c48971e2db3fb79d2cf28d64)
[3ae8fdc](https://github.com/BSData/horus-heresy/pull/3530/commits/3ae8fdc91732faf7c48971e2db3fb79d2cf28d64)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/0572e067b15ec36af5dd6e67da5d419fd0661011) https://github.com/BSData/horus-heresy/issues/3485[: Added bolt pistols to Slayers and Stalkers](https://github.com/BSData/horus-heresy/pull/3530/commits/0572e067b15ec36af5dd6e67da5d419fd0661011)
[0572e06](https://github.com/BSData/horus-heresy/pull/3530/commits/0572e067b15ec36af5dd6e67da5d419fd0661011)

@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/3c47c5d3171200085c2a8f3086dfd879ca241b63) https://github.com/BSData/horus-heresy/issues/3484[: Reavers counting special weapons badly](https://github.com/BSData/horus-heresy/pull/3530/commits/3c47c5d3171200085c2a8f3086dfd879ca241b63)
[3c47c5d](https://github.com/BSData/horus-heresy/pull/3530/commits/3c47c5d3171200085c2a8f3086dfd879ca241b63)
@The4D6
[Fixed](https://github.com/BSData/horus-heresy/pull/3530/commits/3927aeee4cb3312013ff15b1247e7d13a51e208e) https://github.com/BSData/horus-heresy/issues/3470[: Militia rapier carriers had wrong number of laspistols](https://github.com/BSData/horus-heresy/pull/3530/commits/3927aeee4cb3312013ff15b1247e7d13a51e208e)

**Comment by The4D6** [comment]
/release bump=minor

Added the Arvus Lighter!

**Comment by The4D6** [comment]
/release

Made the arvus a standalone FA choice

**Comment by The4D6** [comment]
/release bump=minor

Fixes 7: Many more things

**Comment by The4D6** [comment]
/release

Fixed a bug with the Arvus Lighter

**Comment by The4D6** [comment]
/release bump=minor

Fixes 8: Lots of small validation errors

**Comment by Mayegelt** [comment]
/release bump=minor

Daemons. Daemons everywhere!
Reworked Dominions to work on NR

**Comment by nstephenh** [comment]
/release bump=major

Warsmith Dominus from Warhammer Community

**Comment by nstephenh** [comment]
/release 
Warsmith Dominus warlord trait fix

**Comment by Mayegelt** [comment]
/release bump=minor
Lots of fixes. Still lots to go before 3.0 hits.

- Fix for logic on Bound Daemon Brutes for IT
- Sang Guard in AL
- Militia fix for Forge Remnant in allied detachment as it wasn't allowing the extra HS slots.
- Custodian Guard weapon options lacked min/max 1 missing from the weapons and vex for the previews and stuff.
- Veterans in BS Abberant/Clone issue which was applying even though they didn't have Pride to give them Heart to remove.
- Thallax with 7+ shouldn't have been able to take Triaros
- Blackshields: Panoply of Old (Space Wolves or White Scars) was removing generic Consul options
- 2 SW Special Char restrictions error
- Shattered Legion missed Fury of Ancients Contemptor Talon and Venerable Dread root entries.

**Comment by Mayegelt** [comment]
/release bump
A bunch more. Hopefully not much more to go before 3.0

- Tarantula Sentry Gun Battery
- Xenos Weapons
- Fix for Questoris Warlord Trait.
- Sons of Horus Chieftains weren't showing as compulsory HQ
- Fix for pts on force weapon exchange.
- Blackshields "In Disgrace" fix for Warlord when main detachment.
- Blackshield toxin bombs fix.
- Weapons of Desperation on Mortatis Destroyers pts fix
- Drop pod fix
