### ISSUE TITLE
Master if Legion error on 1500 point list

### ISSUE THREAD

**Issue by jtisdel359** [BSData/horus-heresy#2225]
**Describe the bug**
when creating a 1,500 point list and add a unit with “Master of the Legion”, the error “1 too many selections of Master of the Legion (maximum 0)”.

**To Reproduce**
1. Create an Emperor’s Children loyalist list2. 
2. Set the point limit to 15003. 
3. Add Saul Tarvitz.4. 

**Expected behavior**
Per Liber Hereticus, page 123 under “Master of the Legion” it states “An army may only include a maximum of one model with this special rule per 1,000 points.”

**Comment by Mayegelt** [comment]
Try adding at least 1000pts of stuff to the actual army.
Aka a few tact squads and stuff until you go over 1000pts.

**Comment by jtisdel359** [comment]
Thanks - I still get the error with 1,495 points in the list.

jmt

**Comment by Mayegelt** [comment]
Please post the list and I'll check my end

**Comment by jtisdel359** [comment]
Will do when I get home
Thanks

jmt

**Comment by Mayegelt** [comment]
Looks like testing on PC it is fixed. But it might have been fixed in a currently unreleased push.
Check back after next release.

**Comment by jtisdel359** [comment]
Will do

jmt

**Comment by jtisdel359** [comment]
Attached a roster exhibiting the error.
Battlescribe version: v2.03.21.166
Horus Heresy v16.1.2

**Comment by UrsinePatriarch** [comment]
Still can't replicate on our side, so presuming the recent releases do something that fixes this.

**Comment by jtisdel359** [comment]
Thanks

jmt

**Comment by jtisdel359** [comment]
Nikola,
I've just confirmed this issue is fixed in HH v16.1.3.
Thanks
Jmt
